# =====================================
# SERVER
# =====================================
server.port=8080

# =====================================
# PostgreSQL DATABASE
# =====================================
spring.datasource.url=jdbc:postgresql://postgres:bPHvVqTlDcNqQYkbLsXVVenWjAhGuJhj@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=bPHvVqTlDcNqQYkbLsXVVenWjAhGuJhj
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================
# JPA / HIBERNATE
# =====================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true